### Import

In [1]:
from sklearn import datasets
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

### Load data

In [2]:
iris = datasets.load_iris()
# get only petal length and petal width
X = iris["data"][:, 2:]
# binary classification for (virginica or not virginica)
y = (iris["target"] == 2).astype(np.float64)

### Create pipeline

In [3]:
# rescale data is important for SVM
svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("linear_svc", LinearSVC(C=1, loss="hinge"))
])

### Training

In [4]:
svm_clf.fit(X, y)

Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('linear_svc', LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0))])

### Make prediction

In [5]:
svm_clf.predict([[5.5, 1.7]])

array([1.])

__Note__: Unlike Logistic Regression classifiers, SVM classifiers do not output probabilities for each class

### Alternative options

#### Using SVC class with kernel

Alternatively, you could use the SVC class, using `SVC(kernel="linear", C=1)`, but __it is much slower, especially with large training sets__, so it is not recommended.

In [9]:
from sklearn.svm import SVC

svc_clf =  Pipeline([
    ("scaler", StandardScaler()),
    ("linear_svc", SVC(kernel="linear", C=1))
])

In [10]:
svc_clf.fit(X, y)

Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('linear_svc', SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False))])

In [18]:
svc_clf.predict([[5.5, 1.7]])

array([1.])

#### Using `SGDClassifier` class, with `SGDClassifier(loss="hinge", alpha=1/(m*C))`

- It does __not converge as fast as the LinearSVC class__
- but it can be useful to __handle huge datasets__ that do not fit in memory (out-of-core training)
- or to __handle online classification tasks__.

In [16]:
from sklearn.linear_model import SGDClassifier

m = X.shape[0]
C = 1

sgd_clf =  Pipeline([
    ("scaler", StandardScaler()),
    ("sgd", SGDClassifier(loss="hinge", alpha=1/(m*C), max_iter=300, tol=1e-3,))
])

In [17]:
sgd_clf.fit(X, y)

Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('sgd', SGDClassifier(alpha=0.006666666666666667, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_it..._state=None, shuffle=True, tol=0.001,
       validation_fraction=0.1, verbose=0, warm_start=False))])

In [19]:
sgd_clf.predict([[5.5, 1.7]])

array([1.])